apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tas-llm-router

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment.yaml
- service.yaml
- ingress.yaml

commonLabels:
  app.kubernetes.io/name: llm-router
  app.kubernetes.io/component: api
  app.kubernetes.io/part-of: tas

images:
- name: llm-router
  newName: registry-api.tas.scharber.com/llm-router
  newTag: latest
